# Generated by Django 5.2.11 on 2026-02-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerleave',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainer_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerleave',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='trainers.trainerprofile'),
        ),
        migrations.AddField(
            model_name='traineravailability',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='trainers.trainerprofile'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['user'], name='trainer_pro_user_id_ad33d3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['is_active'], name='trainer_pro_is_acti_64a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['is_verified'], name='trainer_pro_is_veri_dccea6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerleave',
            index=models.Index(fields=['trainer', 'start_date', 'end_date'], name='trainer_lea_trainer_a29b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='traineravailability',
            index=models.Index(fields=['trainer'], name='trainer_ava_trainer_03d12c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traineravailability',
            unique_together={('trainer', 'start_time', 'end_time')},
        ),
    ]
