# Generated by Django 6.0 on 2026-02-03 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerprofile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'trainer_availabilities',
            },
        ),
        migrations.CreateModel(
            name='TrainerLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'trainer_leaves',
            },
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='max_sessions_per_day',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='both', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['is_active'], name='trainer_pro_is_acti_64a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['is_verified'], name='trainer_pro_is_veri_dccea6_idx'),
        ),
        migrations.AddField(
            model_name='traineravailability',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='trainers.trainerprofile'),
        ),
        migrations.AddField(
            model_name='trainerleave',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='trainers.trainerprofile'),
        ),
        migrations.AddIndex(
            model_name='traineravailability',
            index=models.Index(fields=['trainer'], name='trainer_ava_trainer_03d12c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traineravailability',
            unique_together={('trainer', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='trainerleave',
            index=models.Index(fields=['trainer', 'start_date', 'end_date'], name='trainer_lea_trainer_a29b6a_idx'),
        ),
    ]
