# Generated by Django 6.0 on 2026-02-09 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_traineravailability_trainerleave_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerleave',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainer_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerleave',
            name='leave_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
    ]
