# Generated by Django 5.2.11 on 2026-02-26 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('na', 'Prefer not to say')], max_length=20, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fitness_goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('flexibility', 'Flexibility'), ('endurance', 'Endurance')], max_length=100, null=True)),
                ('workout_experience', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=100, null=True)),
                ('preferred_workout_type', models.CharField(blank=True, choices=[('strength_training', 'Strength Training'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('crossfit', 'Crossfit'), ('mixed', 'Mixed')], max_length=50, null=True)),
                ('goal_speed', models.CharField(blank=True, choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('steady', 'Steady'), ('fast', 'Fast')], max_length=50, null=True)),
                ('diet_preference', models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non_veg', 'Non_vegetarian')], max_length=50, null=True)),
                ('daily_activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light Active'), ('moderate', 'Moderately Active'), ('very_active', 'Very active')], max_length=50, null=True)),
                ('target_daily_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('water_goal_ml', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_profiles',
            },
        ),
        migrations.CreateModel(
            name='MealAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('percentage', models.FloatField(default=0.0)),
                ('target_calories', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Meal Allocations',
            },
        ),
    ]
