# Generated by Django 6.0 on 2026-01-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('percentage', models.FloatField(default=0.0)),
                ('target_calories', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_allocations', to='clients.clientprofile')),
            ],
            options={
                'verbose_name_plural': 'Meal Allocations',
                'indexes': [models.Index(fields=['profile', 'meal_type'], name='clients_mea_profile_63d393_idx')],
                'unique_together': {('profile', 'meal_type')},
            },
        ),
    ]
