# Generated by Django 5.2.11 on 2026-02-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealallocation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_allocations', to='clients.clientprofile'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='client_prof_user_id_9c6d10_idx'),
        ),
        migrations.AddIndex(
            model_name='mealallocation',
            index=models.Index(fields=['profile', 'meal_type'], name='clients_mea_profile_63d393_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealallocation',
            unique_together={('profile', 'meal_type')},
        ),
    ]
