# Generated by Django 6.0 on 2026-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_mealallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_workout_type',
            field=models.CharField(blank=True, choices=[('strength_training', 'Strength Training'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('crossfit', 'Crossfit'), ('mixed', 'Mixed')], max_length=50, null=True),
        ),
    ]
