# Generated by Django 5.2.11 on 2026-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_mealallocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='daily_calorie_burn_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
