# Generated by Django 5.2.11 on 2026-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientprofile_daily_calorie_burn_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
