# Generated by Django 6.0 on 2026-02-05 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_mealallocation'),
        ('trainers', '0003_traineravailability_trainerleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled_early', 'Canceled Early'), ('canceled_late', 'Canceled Late'), ('no_show', 'No Show'), ('trainer_unavailable', 'Trainer Unavailable')], default='scheduled', max_length=30)),
                ('created_by_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='clients.clientprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='trainers.trainerprofile')),
            ],
            options={
                'db_table': 'training_sessions',
            },
        ),
        migrations.CreateModel(
            name='DeferredCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_credits', to='clients.clientprofile')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_training.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTrainerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start_time', models.TimeField()),
                ('preferred_end_time', models.TimeField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignment', to='clients.clientprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_clients', to='trainers.trainerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['trainer', 'is_active'], name='personal_tr_trainer_a2b9e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCancellationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('cancellations_used', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_cancellations', to='clients.clientprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'month'], name='personal_tr_client__ddf76c_idx')],
                'unique_together': {('client', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sessions_per_week', models.PositiveIntegerField(default=6)),
                ('session_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='clients.clientprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='personal_training.trainingplan')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'is_active'], name='personal_tr_client__4c6c2d_idx'), models.Index(fields=['plan'], name='personal_tr_plan_id_14a17c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer', 'session_date'], name='training_se_trainer_81a16b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['client', 'session_date'], name='training_se_client__413b24_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer', 'session_date', 'start_time'], name='training_se_trainer_473cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='deferredcredit',
            index=models.Index(fields=['client', 'is_redeemed'], name='personal_tr_client__c79a2e_idx'),
        ),
    ]
