# Generated by Django 5.2.11 on 2026-02-26 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCancellationCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('cancellations_used', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('stripe_raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_product_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('stripe_price_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trainer_share_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_share_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scheduled_start', models.DateTimeField(db_index=True, null=True)),
                ('scheduled_end', models.DateTimeField(db_index=True, null=True)),
                ('room_id', models.CharField(max_length=150, null=True, unique=True)),
                ('video_session_started_at', models.DateTimeField(blank=True, null=True)),
                ('video_session_ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('reassigned', 'Reassigned'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled_early', 'Canceled Early'), ('canceled_late', 'Canceled Late'), ('no_show', 'No Show'), ('trainer_unavailable', 'Trainer Unavailable')], default='scheduled', max_length=30)),
                ('created_by_system', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_trainer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'training_sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Payment Failed')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_session', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sessions_per_week', models.PositiveIntegerField(default=6)),
                ('session_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='clients.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTrainerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start_time', models.TimeField()),
                ('preferred_end_time', models.TimeField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignment', to='clients.clientprofile')),
            ],
        ),
    ]
