# Generated by Django 6.0 on 2026-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-scheduled_start']},
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='cancelled_by_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='room_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='scheduled_end',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='scheduled_start',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='video_session_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='video_session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('reassigned', 'Reassigned'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled_early', 'Canceled Early'), ('canceled_late', 'Canceled Late'), ('no_show', 'No Show'), ('trainer_unavailable', 'Trainer Unavailable')], default='scheduled', max_length=30),
        ),
    ]
