# Generated by Django 5.2.11 on 2026-02-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('personal_training', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttrainerassignment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_clients', to='trainers.trainerprofile'),
        ),
        migrations.AddField(
            model_name='deferredcredit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_credits', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='monthlycancellationcounter',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_cancellations', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_training.clientplan'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['duration_days'], name='training_pl_duratio_21dfec_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['price'], name='training_pl_price_180732_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['is_active'], name='training_pl_is_acti_1366d9_idx'),
        ),
        migrations.AddField(
            model_name='clientplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='personal_training.trainingplan'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='client_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='personal_training.clientplan'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='trainers.trainerprofile'),
        ),
        migrations.AddField(
            model_name='deferredcredit',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_training.trainingsession'),
        ),
        migrations.AddIndex(
            model_name='clienttrainerassignment',
            index=models.Index(fields=['trainer', 'is_active'], name='personal_tr_trainer_a2b9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycancellationcounter',
            index=models.Index(fields=['client', 'month'], name='personal_tr_client__ddf76c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlycancellationcounter',
            unique_together={('client', 'month')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client'], name='personal_tr_client__aade8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client_plan'], name='personal_tr_client__7fc63a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='personal_tr_status_d238b1_idx'),
        ),
        migrations.AddIndex(
            model_name='clientplan',
            index=models.Index(fields=['client', 'is_active'], name='personal_tr_client__4c6c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientplan',
            index=models.Index(fields=['plan'], name='personal_tr_plan_id_14a17c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer', 'session_date'], name='training_se_trainer_81a16b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['client', 'session_date'], name='training_se_client__413b24_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer', 'session_date', 'start_time'], name='training_se_trainer_473cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='deferredcredit',
            index=models.Index(fields=['client', 'is_redeemed'], name='personal_tr_client__c79a2e_idx'),
        ),
    ]
