# Generated by Django 5.2.11 on 2026-04-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0003_alter_clientplan_id_alter_clienttrainerassignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('reassigned', 'Reassigned'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('canceled_early', 'Canceled Early'), ('canceled_late', 'Canceled Late'), ('no_show', 'No Show'), ('trainer_unavailable', 'Trainer Unavailable')], default='scheduled', max_length=30),
        ),
    ]
