# Generated by Django 5.2.11 on 2026-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0003_alter_clientplan_id_alter_clienttrainerassignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
