# Generated by Django 5.2.11 on 2026-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0004_alter_trainingsession_scheduled_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='wallet_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
