# Generated by Django 5.2.11 on 2026-02-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_mealallocation_id'),
        ('personal_training', '0004_trainingplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='clientplan',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientplan',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('stripe_raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clientprofile')),
                ('client_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_training.clientplan')),
            ],
            options={
                'indexes': [models.Index(fields=['client'], name='personal_tr_client__aade8d_idx'), models.Index(fields=['client_plan'], name='personal_tr_client__7fc63a_idx'), models.Index(fields=['status'], name='personal_tr_status_d238b1_idx')],
            },
        ),
    ]
