# Generated by Django 5.2.11 on 2026-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0005_trainingsession_wallet_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={},
        ),
        migrations.RenameField(
            model_name='trainingsession',
            old_name='scheduled_end',
            new_name='client_joined_at',
        ),
        migrations.RenameField(
            model_name='trainingsession',
            old_name='scheduled_start',
            new_name='trainer_joined_at',
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('reassigned', 'Reassigned'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('canceled_early', 'Canceled Early'), ('canceled_late', 'Canceled Late'), ('no_show', 'No Show'), ('trainer_unavailable', 'Trainer Unavailable'), ('cancelled_by_system', 'Cancelled_by_system')], default='scheduled', max_length=30),
        ),
    ]
