# Generated by Django 5.2.11 on 2026-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0005_clientplan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
    ]
