# Generated by Django 5.2.11 on 2026-04-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0006_alter_trainingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='client_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
