# Generated by Django 6.0 on 2026-02-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_clientprofile_preferred_workout_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_data', models.JSONField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan', to='clients.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
