# Generated by Django 5.2.11 on 2026-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdietplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
