# Generated by Django 5.2.11 on 2026-03-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_plan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdietplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
