# Generated by Django 5.2.11 on 2026-02-26 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_date', models.DateField()),
                ('sleep_start', models.DateTimeField()),
                ('sleep_end', models.DateTimeField()),
                ('hours_slept', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sleep_date'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_calories', models.FloatField(default=0.0)),
                ('total_protein', models.FloatField(default=0.0)),
                ('total_carbs', models.FloatField(default=0.0)),
                ('total_fat', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('date_eaten', models.DateField()),
                ('time_eaten', models.TimeField()),
                ('food_description', models.TextField()),
                ('total_calories', models.FloatField(default=0.0)),
                ('protein_grams', models.FloatField(default=0.0)),
                ('carbs_grams', models.FloatField(default=0.0)),
                ('fat_grams', models.FloatField(default=0.0)),
                ('fiber_grams', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('edamam', 'Edamam API')], default='manual', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Meal Entries',
            },
        ),
    ]
