# Generated by Django 6.0 on 2025-12-29 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The date for this summary (e.g., 2025-12-29)')),
                ('total_calories', models.FloatField(default=0.0, help_text='Sum of calories from all MealEntry for this user/date')),
                ('total_protein', models.FloatField(default=0.0, help_text='Total protein in grams')),
                ('total_carbs', models.FloatField(default=0.0, help_text='Total carbs in grams')),
                ('total_fat', models.FloatField(default=0.0, help_text='Total fat in grams')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
                'indexes': [models.Index(fields=['user', 'date'], name='nutrition_d_user_id_9b0282_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner')], help_text='Type of meal or snack (e.g., Breakfast)', max_length=20)),
                ('date_eaten', models.DateField(help_text='Date the meal was consumed (e.g., 2025-12-29)')),
                ('time_eaten', models.TimeField(help_text='Time the meal was eaten (e.g., 08:30)')),
                ('food_description', models.TextField(help_text="Description of the food (e.g., 'Oatmeal with banana')")),
                ('total_calories', models.FloatField(default=0.0, help_text='Total calories for this entry (e.g., 250.0)')),
                ('protein_grams', models.FloatField(default=0.0, help_text='Protein in grams (e.g., 15.0)')),
                ('carbs_grams', models.FloatField(default=0.0, help_text='Carbohydrates in grams (e.g., 40.0)')),
                ('fat_grams', models.FloatField(default=0.0, help_text='Fat in grams (e.g., 5.0)')),
                ('fiber_grams', models.FloatField(default=0.0, help_text='Fiber in grams (e.g., 3.0)')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meal Entries',
                'indexes': [models.Index(fields=['user', 'date_eaten'], name='nutrition_m_user_id_294d30_idx'), models.Index(fields=['user', 'date_eaten', 'meal_type'], name='nutrition_m_user_id_11f509_idx')],
            },
        ),
    ]
