# Generated by Django 6.0 on 2025-12-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('edamam', 'Edamam API')], default='manual', max_length=20),
        ),
    ]
