# Generated by Django 5.2.11 on 2026-02-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysleep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailysleep',
            unique_together={('user', 'sleep_date')},
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['user', 'date'], name='nutrition_d_user_id_9b0282_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='mealentry',
            index=models.Index(fields=['user', 'date_eaten'], name='nutrition_m_user_id_294d30_idx'),
        ),
        migrations.AddIndex(
            model_name='mealentry',
            index=models.Index(fields=['user', 'date_eaten', 'meal_type'], name='nutrition_m_user_id_11f509_idx'),
        ),
    ]
