# Generated by Django 6.0 on 2026-01-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_mealentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='carbs_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='date_eaten',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='fat_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='fiber_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='food_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='protein_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='time_eaten',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='total_calories',
            field=models.FloatField(default=0.0),
        ),
    ]
