"""
Django settings for kaaizen project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
#for env variable 
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG",cast=bool)

ALLOWED_HOSTS = [
    "kaaizen.shaheem.site",
    "localhost",
    "127.0.0.1",
    "13.201.67.122",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #third party
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    
    #apps
    'core',
    'users',
    'auth_api',
    'clients',
    'admin_api',
    'nutrition',
    'workouts',
    'trainers',
    'personal_training',
    'ai_plan',
    'wallet',
    'notification'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kaaizen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kaaizen.wsgi.application'


AUTH_USER_MODEL = "users.User"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),        
        'USER': config('DB_USER'),           
        'PASSWORD': config('DB_PASSWORD'),   
        'HOST': 'localhost',          
        'PORT': config('DB_PORT'),               
    }
}
# 'localhost'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#initial tasks
CORS_ALLOWED_ORIGINS = [
    config('FRONTEND_URL'),
]

CORS_ALLOW_CREDENTIALS = True


REST_FRAMEWORK = {
    
    "EXCEPTION_HANDLER": "kaaizen.exceptions.custom_exception_handler",

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'auth_api.utils.jwt_authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


# redis
import redis

REDIS_CLIENT = redis.Redis(
    host=config('REDIS_HOST'),
    port=config('REDIS_PORT'),
    decode_responses=True,
    username=config('REDIS_USERNAME'),
    password=config('REDIS_PASSWORD'),
)



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Email configurations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


#GOOGGLE AUTH
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')



# EDAMAM
EDAMAM_APP_ID = config('EDAMAM_APP_ID')
EDAMAM_APP_KEY = config('EDMAM_APP_KEY')




# Cloudinary
import cloudinary

CLOUDINARY_CLOUD_NAME = config("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = config("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = config("CLOUDINARY_API_SECRET")

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)


# Logger
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "django.log",
            "formatter": "verbose",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "": {  # Root logger
            "handlers": ["console", "file"],
            "level": "DEBUG",
        },
    },
}


# zegocloud 
ZEGO_APP_ID = config("ZEGO_APP_ID")
ZEGO_SERVER_SECRET = config("ZEGO_SERVER_SECRET")



#gemini
GEMINI_API_KEY = config("GEMINI_API_KEY")


#celery 
CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND')


CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = False


# configuring periodic task
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {

    #  Personal Training 
    "maintain-rolling-sessions": {
        "task": "personal_training.tasks.maintain_sessions",
        "schedule": crontab(hour=2, minute=0),
    },

    # Wallet Settlement 
    "admin-daily-settlement": {
        "task": "wallet.tasks.run_admin_daily_settlement",
        "schedule": crontab(hour=2, minute=0),
    },

    #  Tracking Reminder 
    "send-tracking-reminders-every-minute": {
        "task": "notification.tasks.send_tracking_reminder.send_tracking_reminders",
        "schedule": crontab(minute=0, hour="*/2"),   
    },
}


#stripe
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET")



# frontend
FRONTEND_URL = config('FRONTEND_URL')



# firebase
import core.firebase