# Generated by Django 5.2.11 on 2026-02-26 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Muscle Group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Workout Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('video_url', models.URLField(max_length=500)),
                ('video_public_id', models.CharField(max_length=250)),
                ('thumbnail_time', models.FloatField(default=2.0)),
                ('equipment_needed', models.TextField(blank=True, null=True)),
                ('met_value', models.FloatField(default=0.0)),
                ('muscle_groups', models.ManyToManyField(blank=True, related_name='workouts', to='workouts.musclegroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.workoutcategory')),
            ],
            options={
                'verbose_name': 'Workout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('total_calories_burned', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'User Favorite Workout',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'workout')},
            },
        ),
        migrations.CreateModel(
            name='SessionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_play_time_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_entries', to='workouts.workout')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_videos', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name': 'Session Video',
                'ordering': ['started_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'workout'), name='unique_video_per_session')],
            },
        ),
    ]
