# Generated by Django 6.0 on 2026-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcategory',
            name='category_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
